blank_issues_enabled: false
contact_links:
  - name: Feature request or idea
    url: https://github.com/Relaticle/relaticle/discussions/new?category=ideas
    about: Share ideas for new features or improvements
  - name: Support question
    url: https://github.com/Relaticle/relaticle/discussions/new?category=q-a
    about: Ask the community for help
